### ISSUE TITLE
How to extract Sleeping Dogs .big/.bix  file?

### ISSUE THREAD

**Issue by siuhamlop** [sneakyevil/SD-UltimateTexTool#1]
Hello, I am from Hong Kong and I loved this game so much, I want to change all those fake shop logo to real thing but I have tried many .big extractor still cannot open the .big file. Can you teach how to do it?

**Comment by sneakyevil** [comment]
> Hello, I am from Hong Kong and I loved this game so much, I want to change all those fake shop logo to real thing but I have tried many .big extractor still cannot open the .big file. Can you teach how to do it?

https://mega.nz/file/CeJhwIaZ#gL0Byx7utvwSNVdVdn49319_2RPu-5_PzkL4_F_xPDY
